name: ci-cd-workflow

on:
   push:
      branches: ["main"]
      paths-ignore:
         - "**/*.md"
         - "**/*.gitignore"
         - "**/*.gitattributes"
   pull_request:
      branches: ["main"]

env:
   DOTNET_NOLOGO: true
   DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
   DOTNET_CLI_TELEMETRY_OPTOUT: true
   dotnet_version: 9.0.x

jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v4

         - name: Setup .Net
           uses: actions/setup-dotnet@v4
           with:
              dotnet-version: 9.0.x

         - name: Restore dependencies
           run: dotnet restore
           working-directory: .

         - name: Format code
           run: dotnet format .
           working-directory: .

         - name: Build application
           run: dotnet build --no-restore
           working-directory: .

         - name: Run test(s)
           run: dotnet test --no-build --verbosity normal
