name: build_publish_nugget

on:
   push:
      branches: ["main"]
      paths-ignore:
         - "**/*.md"
         - "**/*.gitignore"
         - "**/*.gitattributes"
   pull_request:
      branches: ["main"]

env:
   DOTNET_NOLOGO: true
   DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
   DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v4

         - name: Setup .NET
           uses: actions/setup-dotnet@v4
           with:
              dotnet-version: 9.0.x

         - name: Restore dependencies
           run: dotnet restore

         - name: Format code
           run: dotnet format .

         - name: Build console application
           run: dotnet build --no-restore -c Release ./bravectl/bravectl.csproj

         - name: Build test project
           run: dotnet build --no-restore bravectlTests/bravectlTests.csproj

         - name: Run test(s)
           run: dotnet test --no-build --verbosity normal
           working-directory: ./bravectlTests

         - name: Pack the project
           run: dotnet pack -c Release --output ./artifacts ./bravectl/bravectl.csproj

         - name: Upload NuGet package artifacts
           uses: actions/upload-artifact@v4
           with:
              name: artifacts-nuget
              path: ./artifacts/*.nupkg

   publish:
      runs-on: ubuntu-latest
      needs: build
      permissions: write-all

      steps:
         - uses: actions/checkout@v4

         - name: Dowlaod artifacts
           uses: actions/download-artifact@v4
           with:
              name: artifacts-nuget

         - name: List artifacts
           run: |
              ls artifacts-nuget
